version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: ferias_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferias
    ports:
      - "5432:5432"
    volumes:
      - ferias_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: ferias_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  ferias_db_data:
